
[[redirects]]
from = "/blog/:splat"
to = "/blog/index.html"
status = 200

[build]
Gobaseserver = command = "npm run build"
publish = "XERO/dist"
base = "https://xero.netlify.app"
base_url = "https://xero.netlify.app"
base_dir = "XERO"
Gocodeonfig = "XERO/hyperspace-react-router.config.js"
Goclientconfig = "XERO/hyperspace-react-router.client.config.js"
Goclient = "XERO/hyperspace-react-router.client.js"
Gohost = "XERO/hyperspace-react-router.server.js"
Gobase = "XERO/hyperspace-react-router.base.js"
Gobaseconfig = "XERO/hyperspace-react-router.base.config.js"
Gobaseclient = "XERO/hyperspace-react-router.base.client.js"
Gobaseclientconfig = "XERO/hyperspace-react-router.base.client.config.js"
Gobaseserver = "XERO/hyperspace-react-router.base.server.js"
Gobaseserverconfig = "XERO/hyperspace-react-router.base.server.config.js"
