[build]
command = "npm run build"
publish = "XERO/dist"

[[redirects]]
from = "/blog/:splat"
to = "/blog/index.html"
status = 200

[context.production.environment]
NODE_ENV = "production"
REACT_APP_BASE_URL = "https://xero.netlify.app"
REACT_APP_BASE_DIR = "XERO"
REACT_APP_GOBASE = "XERO/hyperspace-react-router.base.js"
REACT_APP_GOBASECONFIG = "XERO/hyperspace-react-router.base.config.js"
REACT_APP_GOBASECLIENT = "XERO/hyperspace-react-router.base.client.js"
REACT_APP_GOBASECLIENTCONFIG = "XERO/hyperspace-react-router.base.client.config.js"
REACT_APP_GOBASESERVER = "XERO/hyperspace-react-router.base.server.js"
REACT_APP_GOBASESERVERCONFIG = "XERO/hyperspace-react-router.base.server.config.js"
[context.development.environment]
NODE_ENV = "development"
REACT_APP_BASE_URL = "http://localhost:3000"
REACT_APP_BASE_DIR = "XERO"
REACT_APP_GOBASE = "XERO/hyperspace-react-router.base.js"
REACT_APP_GOBASECONFIG = "XERO/hyperspace-react-router.base.config.js"
REACT_APP_GOBASECLIENT = "XERO/hyperspace-react-router.base.client.js"
REACT_APP_GOBASECLIENTCONFIG = "XERO/hyperspace-react-router.base.client.config.js"
REACT_APP_GOBASESERVER = "XERO/hyperspace-react-router.base.server.js"
REACT_APP_GOBASESERVERCONFIG = "XERO/hyperspace-react-router.base.server.config.js"
